<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>XML Sitemap Index &#8211; ToolBox URL</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="robots" content="noindex,follow" />
  <style type="text/css">
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      color: #1a1a2e;
      background: #f8f9fa;
      font-size: 14px;
      line-height: 1.6;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      padding: 0 20px;
    }
    .header {
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      color: white;
      padding: 32px 0;
      margin-bottom: 24px;
    }
    .header h1 {
      font-size: 22px;
      font-weight: 700;
      margin-bottom: 6px;
    }
    .header p {
      font-size: 14px;
      opacity: 0.9;
    }
    .header a {
      color: white;
      text-decoration: underline;
    }
    .summary {
      background: white;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 16px 20px;
      margin-bottom: 20px;
      font-size: 13px;
      color: #64748b;
    }
    .summary strong { color: #1a1a2e; }
    table {
      width: 100%;
      border-collapse: collapse;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      border: 1px solid #e2e8f0;
      margin-bottom: 40px;
    }
    th {
      background: #f1f5f9;
      padding: 14px 20px;
      text-align: left;
      font-weight: 600;
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #475569;
      border-bottom: 2px solid #e2e8f0;
    }
    td {
      padding: 14px 20px;
      border-bottom: 1px solid #f1f5f9;
      font-size: 14px;
    }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8fafc; }
    td a {
      color: #6366f1;
      text-decoration: none;
      font-weight: 500;
    }
    td a:hover { text-decoration: underline; }
    .badge {
      display: inline-block;
      background: #ede9fe;
      color: #6366f1;
      padding: 2px 10px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      margin-left: 8px;
    }
    .footer {
      text-align: center;
      padding: 20px 0 40px;
      font-size: 12px;
      color: #94a3b8;
    }
    .footer a { color: #6366f1; text-decoration: none; }
    @media (max-width: 768px) {
      th, td { padding: 10px 14px; font-size: 13px; }
      .header h1 { font-size: 18px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="container">
      <h1>XML Sitemap Index</h1>
      <p>Generated by <a href="https://toolboxurl.com">ToolBox URL</a> &#8212; Free Developer Tools</p>
    </div>
  </div>
  <div class="container">
    <div class="summary">
      This sitemap index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
    </div>
    <table>
      <thead>
        <tr>
          <th style="width:5%">#</th>
          <th>Sitemap</th>
          <th style="width:22%">Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
          <tr>
            <td><xsl:value-of select="position()"/></td>
            <td>
              <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
            </td>
            <td><xsl:value-of select="sitemap:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
    <div class="footer">
      Generated by <a href="https://toolboxurl.com">ToolBox URL</a>
    </div>
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
